name: Kernel Config - Custom

permissions:
  contents: write
  actions: write

on:
  workflow_call:
    inputs:
      ksu_variant:
        required: true
        type: string
      ksu_commit:
        required: false
        type: string
      build_bypass:
        required: true
        type: boolean

jobs:
  build-kernel-custom:
    strategy:
      fail-fast: false
      matrix:
        include:
        - android_version: "android12"
          kernel_version: "5.10"
          sub_level: "226"
          os_patch_level: "2024-11"
          variant: "vTomsonek"
        - android_version: "android14"
          kernel_version: "6.1"
          sub_level: "145"
          os_patch_level: "2025-09"
          variant: "TheWildJames"
        - android_version: "android14"
          kernel_version: "6.1"
          sub_level: "157"
          os_patch_level: "2025-12"
          variant: "MarionKernel"
        - android_version: "android14"
          kernel_version: "6.1"
          sub_level: "128"
          os_patch_level: "2025-03"
          variant: "Hakan"
        - android_version: "android14"
          kernel_version: "6.1"
          sub_level: "68"
          os_patch_level: "2024-03"
          variant: "Duchamp"

    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      android_version: ${{ matrix.android_version }}
      kernel_version: ${{ matrix.kernel_version }}
      sub_level: ${{ matrix.sub_level }}
      os_patch_level: ${{ matrix.os_patch_level }}
      variant: ${{ matrix.variant }}
      ksu_variant: ${{ inputs.ksu_variant }}
      ksu_commit: ${{ inputs.ksu_commit }}
      build_bypass: ${{ inputs.build_bypass }}
