name: Kernel Config - A16 6.12

permissions:
  contents: write
  actions: write

on:
  workflow_call:
    inputs:
      ksu_commit:
        required: false
        type: string
      build_bypass:
        required: true
        type: boolean

jobs:
  build-kernels-a16-612:
    name: "6.12.${{ matrix.sub_level }}-${{ matrix.os_patch_level }}"
    strategy:
      fail-fast: false
      matrix:
        include:
        - sub_level: "23"
          os_patch_level: "2025-05-exp"
        - sub_level: "30"
          os_patch_level: "2025-07"
        - sub_level: "38"
          os_patch_level: "2025-08"
        - sub_level: "38"
          os_patch_level: "2025-09"
        - sub_level: "58"
          os_patch_level: "2025-12"
        # Add more sublevels/patch levels as needed
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      android_version: "android16"
      kernel_version: "6.12"
      sub_level: ${{ matrix.sub_level }}
      os_patch_level: ${{ matrix.os_patch_level }}
      variant: "A16-612"
      ksu_commit: ${{ inputs.ksu_commit }}
      build_bypass: ${{ inputs.build_bypass }}
