name: Kernel Config - A12 5.10

permissions:
  contents: write # Allow writing to repository contents
  actions: write # Allows triggering actions

on:
  workflow_call:
    inputs:
      ksu_commit:
        required: false
        type: string
      build_bypass:
        required: true
        type: boolean

jobs:
  build-kernels-a12:
    name: "5.10.${{ matrix.sub_level }}-${{ matrix.os_patch_level }}"
    strategy:
      fail-fast: false
      matrix:
        include:
        # Deprecated series (Android 12 - 5.10)
        - sub_level: "43"
          os_patch_level: "2021-08"
        - sub_level: "43"
          os_patch_level: "2021-09"
        - sub_level: "43"
          os_patch_level: "2021-10"
        - sub_level: "66"
          os_patch_level: "2021-11"
        - sub_level: "66"
          os_patch_level: "2021-12"
        - sub_level: "66"
          os_patch_level: "2022-01"
        - sub_level: "81"
          os_patch_level: "2022-02"
        - sub_level: "81"
          os_patch_level: "2022-03"
        - sub_level: "101"
          os_patch_level: "2022-04"
        - sub_level: "101"
          os_patch_level: "2022-05"
        - sub_level: "110"
          os_patch_level: "2022-06"
        - sub_level: "110"
          os_patch_level: "2022-07"
        - sub_level: "117"
          os_patch_level: "2022-08"
        - sub_level: "117"
          os_patch_level: "2022-09"
        - sub_level: "136"
          os_patch_level: "2022-10"
        - sub_level: "136"
          os_patch_level: "2022-11"
        - sub_level: "149"
          os_patch_level: "2022-12"
        - sub_level: "149"
          os_patch_level: "2023-01"
        - sub_level: "160"
          os_patch_level: "2023-02"
        - sub_level: "160"
          os_patch_level: "2023-03"
        - sub_level: "168"
          os_patch_level: "2023-04"
        - sub_level: "168"
          os_patch_level: "2023-05"
        - sub_level: "177"
          os_patch_level: "2023-06"
        - sub_level: "177"
          os_patch_level: "2023-07"
        - sub_level: "185"
          os_patch_level: "2023-09"
        - sub_level: "198"
          os_patch_level: "2023-11"
        - sub_level: "198"
          os_patch_level: "2024-01"
        - sub_level: "205"
          os_patch_level: "2024-03"
        - sub_level: "209"
          os_patch_level: "2024-05"
        - sub_level: "218"
          os_patch_level: "2024-08"
        # Active series
        - sub_level: "226"
          os_patch_level: "2024-11"
        - sub_level: "233"
          os_patch_level: "2025-02"
        - sub_level: "236"
          os_patch_level: "2025-05"
        - sub_level: "237"
          os_patch_level: "2025-06"
        - sub_level: "240"
          os_patch_level: "2025-09"
        - sub_level: "246"
          os_patch_level: "2025-12"
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      android_version: "android12"
      kernel_version: "5.10"
      sub_level: ${{ matrix.sub_level }}
      os_patch_level: ${{ matrix.os_patch_level }}
      ksu_commit: ${{ inputs.ksu_commit }}
      build_bypass: ${{ inputs.build_bypass }}
