name: Kernel Config - A14 6.1

permissions:
  contents: write # Allow writing to repository contents
  actions: write # Allows triggering actions

on:
  workflow_call:
    inputs:
      ksu_commit:
        required: false
        type: string
      build_bypass:
        required: true
        type: boolean

jobs:
  build-kernels-a14-6-1:
    name: "6.1.${{ matrix.sub_level }}-${{ matrix.os_patch_level }}"
    strategy:
      fail-fast: false
      matrix:
        include:
        - sub_level: "25"
          os_patch_level: "2023-06"
        - sub_level: "25"
          os_patch_level: "2023-07"
        - sub_level: "25"
          os_patch_level: "2023-08"
        - sub_level: "25"
          os_patch_level: "2023-09"
        - sub_level: "25"
          os_patch_level: "2023-10"
        - sub_level: "43"
          os_patch_level: "2023-11"
        - sub_level: "57"
          os_patch_level: "2023-12"
        - sub_level: "57"
          os_patch_level: "2024-01"
        - sub_level: "68"
          os_patch_level: "2024-02"
        - sub_level: "68"
          os_patch_level: "2024-03"
        - sub_level: "75"
          os_patch_level: "2024-04"
        - sub_level: "75"
          os_patch_level: "2024-05"
        - sub_level: "78"
          os_patch_level: "2024-06"
        - sub_level: "84"
          os_patch_level: "2024-07"
        - sub_level: "90"
          os_patch_level: "2024-08"
        - sub_level: "93"
          os_patch_level: "2024-09"
        - sub_level: "99"
          os_patch_level: "2024-10"
        - sub_level: "112"
          os_patch_level: "2024-11"
        - sub_level: "115"
          os_patch_level: "2024-12"
        - sub_level: "118"
          os_patch_level: "2025-01"
        - sub_level: "124"
          os_patch_level: "2025-02"
        - sub_level: "128"
          os_patch_level: "2025-03"
        - sub_level: "129"
          os_patch_level: "2025-04"
        - sub_level: "134"
          os_patch_level: "2025-05"
        - sub_level: "138"
          os_patch_level: "2025-06"
        - sub_level: "141"
          os_patch_level: "2025-07"
        - sub_level: "145"
          os_patch_level: "2025-08"
        - sub_level: "145"
          os_patch_level: "2025-09"
        - sub_level: "157"
          os_patch_level: "2025-12"
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      android_version: "android14"
      kernel_version: "6.1"
      sub_level: ${{ matrix.sub_level }}
      os_patch_level: ${{ matrix.os_patch_level }}
      ksu_commit: ${{ inputs.ksu_commit }}
      build_bypass: ${{ inputs.build_bypass }}
